//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : autodb
	/// Data Source    : 127.0.0.1
	/// Server Version : 5.7.18-log
	/// </summary>
	public partial class AutodbDB : LinqToDB.Data.DataConnection
	{
		public ITable<Datacar>   Datacars   { get { return this.GetTable<Datacar>(); } }
		public ITable<Good>      Goods      { get { return this.GetTable<Good>(); } }
		public ITable<Order>     Orders     { get { return this.GetTable<Order>(); } }
		public ITable<Payer>     Payers     { get { return this.GetTable<Payer>(); } }
		public ITable<Recipient> Recipients { get { return this.GetTable<Recipient>(); } }
		public ITable<Supplier>  Suppliers  { get { return this.GetTable<Supplier>(); } }
		public ITable<Work>      Works      { get { return this.GetTable<Work>(); } }

		public AutodbDB()
		{
			InitDataContext();
		}

		public AutodbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("datacar")]
	public partial class Datacar
	{
		[PrimaryKey, NotNull    ] public string Car        { get; set; } // varchar(45)
		[Column,        Nullable] public string NumBody    { get; set; } // varchar(45)
		[Column,        Nullable] public string TypeIngine { get; set; } // varchar(45)
		[Column,        Nullable] public string Year       { get; set; } // varchar(45)
		[Column,        Nullable] public string NumIngine  { get; set; } // varchar(45)
		[Column,        Nullable] public string NumCountry { get; set; } // varchar(45)
		[Column,        Nullable] public string Agregat    { get; set; } // varchar(45)
		[Column,        Nullable] public int?   VIN        { get; set; } // int(11)
	}

	[Table("goods")]
	public partial class Good
	{
		[Column("Name of goods"), PrimaryKey,  NotNull] public string NameOfGoods   { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string UnitOfMeasure { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string Amount        { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string Price         { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string Sum           { get; set; } // varchar(45)
	}

	[Table("order")]
	public partial class Order
	{
		[Column(),          PrimaryKey,  NotNull] public DateTime  Number { get; set; } // datetime
		[Column("Дата от"),    Nullable         ] public DateTime? ДатаОт { get; set; } // date
	}

	[Table("payer")]
	public partial class Payer
	{
		[Column("Name of payers"), PrimaryKey,  NotNull] public string NameOfPayers { get; set; } // varchar(45)
		[Column(),                    Nullable         ] public string Address      { get; set; } // varchar(45)
		[Column(),                    Nullable         ] public string City         { get; set; } // varchar(45)
		[Column(),                    Nullable         ] public string Tel          { get; set; } // varchar(45)
		[Column(),                    Nullable         ] public string Email        { get; set; } // varchar(45)
		[Column(),                    Nullable         ] public string Index        { get; set; } // varchar(45)
		[Column(),                    Nullable         ] public string Mob          { get; set; } // varchar(45)
	}

	[Table("recipient")]
	public partial class Recipient
	{
		[Column(),        PrimaryKey,  NotNull] public string Recip  { get; set; } // varchar(35)
		[Column(),           Nullable         ] public string Adress { get; set; } // varchar(35)
		[Column(),           Nullable         ] public string City   { get; set; } // varchar(35)
		[Column(),           Nullable         ] public string Tel    { get; set; } // varchar(35)
		[Column(),           Nullable         ] public string Email  { get; set; } // varchar(35)
		[Column("index"),    Nullable         ] public string Index  { get; set; } // varchar(35)
		[Column(),           Nullable         ] public string Mob    { get; set; } // varchar(35)
	}

	[Table("supplier")]
	public partial class Supplier
	{
		[PrimaryKey, NotNull    ] public string NameOfOrganiz { get; set; } // varchar(45)
		[Column,        Nullable] public string Country       { get; set; } // varchar(45)
		[Column,        Nullable] public string Index         { get; set; } // varchar(45)
		[Column,        Nullable] public string City          { get; set; } // varchar(45)
		[Column,        Nullable] public string Street        { get; set; } // varchar(45)
		[Column,        Nullable] public string NumberOffice  { get; set; } // varchar(45)
		[Column,        Nullable] public string Tel1          { get; set; } // varchar(45)
		[Column,        Nullable] public string Tel2          { get; set; } // varchar(45)
		[Column,        Nullable] public string Email         { get; set; } // varchar(45)
		[Column,        Nullable] public string Account       { get; set; } // varchar(45)
		[Column,        Nullable] public string Bank          { get; set; } // varchar(45)
		[Column,        Nullable] public string MFO           { get; set; } // varchar(45)
		[Column,        Nullable] public string EDRPOU        { get; set; } // varchar(45)
		[Column,        Nullable] public string CodeInd       { get; set; } // varchar(45)
		[Column,        Nullable] public string NumberSvid    { get; set; } // varchar(45)
	}

	[Table("works")]
	public partial class Work
	{
		[Column("Name of works"), PrimaryKey,  NotNull] public string NameOfWorks   { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string UnitOfMeasure { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string Amount        { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string Price         { get; set; } // varchar(45)
		[Column(),                   Nullable         ] public string Sum           { get; set; } // varchar(45)
	}

	public static partial class TableExtensions
	{
		public static Datacar Find(this ITable<Datacar> table, string Car)
		{
			return table.FirstOrDefault(t =>
				t.Car == Car);
		}

		public static Good Find(this ITable<Good> table, string NameOfGoods)
		{
			return table.FirstOrDefault(t =>
				t.NameOfGoods == NameOfGoods);
		}

		public static Order Find(this ITable<Order> table, DateTime Number)
		{
			return table.FirstOrDefault(t =>
				t.Number == Number);
		}

		public static Payer Find(this ITable<Payer> table, string NameOfPayers)
		{
			return table.FirstOrDefault(t =>
				t.NameOfPayers == NameOfPayers);
		}

		public static Recipient Find(this ITable<Recipient> table, string Recip)
		{
			return table.FirstOrDefault(t =>
				t.Recip == Recip);
		}

		public static Supplier Find(this ITable<Supplier> table, string NameOfOrganiz)
		{
			return table.FirstOrDefault(t =>
				t.NameOfOrganiz == NameOfOrganiz);
		}

		public static Work Find(this ITable<Work> table, string NameOfWorks)
		{
			return table.FirstOrDefault(t =>
				t.NameOfWorks == NameOfWorks);
		}
	}
}
